# Generated by Django 5.2 on 2025-09-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalqType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='نوع طلق')),
                ('tables', models.ManyToManyField(to='table.tablematerial', verbose_name='میز ها')),
            ],
            options={
                'verbose_name': 'نوع طلق',
                'verbose_name_plural': 'نوع طلق',
            },
        ),
        migrations.CreateModel(
            name='Talq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField(verbose_name='ضخامت')),
                ('width', models.PositiveIntegerField(verbose_name='عرض')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('talq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talq.talqtype', verbose_name='نوع طلق')),
            ],
            options={
                'verbose_name': 'طلق',
                'verbose_name_plural': 'طلق',
            },
        ),
        migrations.CreateModel(
            name='TalqTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talq_image/', verbose_name='عکس')),
                ('talq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talq.talqtype', verbose_name='نوع طلق')),
            ],
            options={
                'verbose_name': 'عکس نوع طلق',
                'verbose_name_plural': 'عکس نوع طلق',
            },
        ),
    ]
