# Generated by Django 5.2 on 2025-09-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField(verbose_name='ضخامت')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('talq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talq.talqtype', verbose_name='نوع طلق')),
            ],
            options={
                'verbose_name': 'طلق',
                'verbose_name_plural': 'طلق',
            },
        ),
    ]
