# Generated by Django 5.2 on 2025-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talq', '0002_talq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talq',
            name='width',
            field=models.PositiveIntegerField(verbose_name='عرض'),
        ),
    ]
