# Generated by Django 5.2 on 2025-09-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('lng', models.FloatField(verbose_name='طول جغرافیایی')),
                ('lat', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('post_method', models.SmallIntegerField(choices=[(0, 'به شیراز'), (1, 'به شهر دیگر'), (2, 'درب فروشگاه')], verbose_name='روش ارسال')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('authority', models.CharField(max_length=255, verbose_name='کد پرداخت')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=255, verbose_name='نوع میز')),
                ('table_material', models.CharField(max_length=255, verbose_name='جنس میز')),
                ('talq_type', models.CharField(max_length=255, verbose_name='طلق')),
                ('shape', models.CharField(max_length=255, verbose_name='شکل')),
                ('thickness', models.FloatField(verbose_name='ضخامت')),
                ('length', models.FloatField(verbose_name='طول')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/', verbose_name='تصویر')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.orderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'عکس آیتم ها',
                'verbose_name_plural': 'عکس آیتم ها',
            },
        ),
    ]
