# Generated by Django 5.2 on 2025-09-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('lng', models.FloatField(verbose_name='طول جغرافیایی')),
                ('lat', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('post_method', models.IntegerField(verbose_name='روش ارسال')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('authority', models.CharField(max_length=255, verbose_name='احرازهویت')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('table_type', models.IntegerField(verbose_name='نوع میز')),
                ('table_material', models.IntegerField(verbose_name='جنس میز')),
                ('talq_type', models.IntegerField(verbose_name='نوع طلق')),
                ('shape', models.CharField(max_length=50, verbose_name='شکل')),
                ('thickness', models.FloatField(verbose_name='ضخامت')),
                ('length', models.FloatField(verbose_name='طول')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('images', models.JSONField(verbose_name='تصاویر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش مربوطه')),
            ],
        ),
    ]
