# Generated by Django 5.2 on 2025-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_images_orderitemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(max_length=255, verbose_name='کد پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_method',
            field=models.SmallIntegerField(choices=[(0, 'به شیراز'), (1, 'به شهر دیگر'), (2, 'درب فروشگاه')], verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shape',
            field=models.CharField(max_length=255, verbose_name='شکل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='table_material',
            field=models.CharField(max_length=255, verbose_name='جنس میز'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='table_type',
            field=models.CharField(max_length=255, verbose_name='نوع میز'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='talq_type',
            field=models.CharField(max_length=255, verbose_name='طلق'),
        ),
    ]
