# Generated by Django 5.2 on 2025-08-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میز',
            },
        ),
        migrations.CreateModel(
            name='TableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='table_image/')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.table', verbose_name='عنوان میز')),
            ],
            options={
                'verbose_name': 'عکس میز',
                'verbose_name_plural': 'عکس میز',
            },
        ),
    ]
