# Generated by Django 5.2 on 2025-08-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'جنس میز',
                'verbose_name_plural': 'جنس میز',
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع میز',
                'verbose_name_plural': 'نوع میز',
            },
        ),
        migrations.RemoveField(
            model_name='tableimage',
            name='table',
        ),
        migrations.CreateModel(
            name='TableMaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='table_material_image/')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tablematerial', verbose_name='عنوان میز')),
            ],
            options={
                'verbose_name': 'عکس جنس میز',
                'verbose_name_plural': 'عکس جنس میز',
            },
        ),
        migrations.CreateModel(
            name='TableTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='table_type_image/')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tabletype', verbose_name='عنوان میز')),
            ],
            options={
                'verbose_name': 'عکس نوع میز',
                'verbose_name_plural': 'عکس نوع میز',
            },
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableImage',
        ),
    ]
